version: "2"
services:

  seefoodbot:
    image: 974359815377.dkr.ecr.us-east-1.amazonaws.com/seefoodbot:latest
    build: './'
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - web.env
    container_name: seefoodbot